<?xml version="1.0" encoding="utf-8"?><Database Name="Figures" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.bid" Member="bids">
    <Type Name="bid">
      <Column Name="bid_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="item_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="bid_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="catalog_bid" Member="catalog" ThisKey="item_id" OtherKey="item_id" Type="catalog" IsForeignKey="true" />
      <Association Name="user_bid" Member="user" ThisKey="user_id" OtherKey="user_id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.catalog" Member="catalogs">
    <Type Name="catalog">
      <Column Name="item_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="seller_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Imgs" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="listed_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="starts_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ends_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="catalog_bid" Member="bids" ThisKey="item_id" OtherKey="item_id" Type="bid" />
      <Association Name="catalog_purchase" Member="purchases" ThisKey="item_id" OtherKey="item_id" Type="purchase" />
      <Association Name="user_catalog" Member="user" ThisKey="seller_id" OtherKey="user_id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.payment" Member="payments">
    <Type Name="payment">
      <Column Name="payment_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="purchase_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="method" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="paid_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="purchase_payment" Member="purchase" ThisKey="purchase_id" OtherKey="purchase_id" Type="purchase" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.purchase" Member="purchases">
    <Type Name="purchase">
      <Column Name="purchase_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="item_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="buyer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total_amount" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="purchased_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="purchase_payment" Member="payments" ThisKey="purchase_id" OtherKey="purchase_id" Type="payment" />
      <Association Name="catalog_purchase" Member="catalog" ThisKey="item_id" OtherKey="item_id" Type="catalog" IsForeignKey="true" />
      <Association Name="user_purchase" Member="user" ThisKey="buyer_id" OtherKey="user_id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="role" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="user_bid" Member="bids" ThisKey="user_id" OtherKey="user_id" Type="bid" />
      <Association Name="user_catalog" Member="catalogs" ThisKey="user_id" OtherKey="seller_id" Type="catalog" />
      <Association Name="user_purchase" Member="purchases" ThisKey="user_id" OtherKey="buyer_id" Type="purchase" />
    </Type>
  </Table>
</Database>